Repository carbon-design-system/carbon-components-vue, pull requests merged in 2023-11, with the labels that each got.

#1520 docs: cv-file-uploader docs enhancements
  .storybook/manager.js
  .storybook/postinstall.js
  package.json
  src/components/CvFileUploader/CvFileUploader.stories.mdx
  src/components/CvFileUploader/CvFileUploaderItem.vue
  src/components/CvFileUploader/__tests__/CvFileUploaderItem.spec.js
Labels: V3 - Vue 3, hacktoberfest, status: ready to merge

#1539 test(cv-link): add tests for a11y
  src/components/CvLink/CvLink.vue
  src/components/CvLink/__tests__/CvLink.accessibility.spec.js
Labels: hacktoberfest, status: ready to merge

#1552 chore: fix in-flight updates that were active when the lint rules cha…
  src/components/CvProgress/CvProgressSkeleton.vue
Labels: status: ready to merge
